### ISSUE TITLE
Download .obj is directing to localhost on website

### ISSUE THREAD

**Issue by armthethinker** [cindyloo/vrdoodler#31]
<img width="765" alt="screen shot 2016-04-24 at 11 43 32 pm" src="https://cloud.githubusercontent.com/assets/5367025/14771024/7f6bb542-0a76-11e6-84f7-9468f1c4aa9e.png">

Additionally, the .obj I get won't load in A-Frame or Meshmixer.

**Comment by cindyloo** [comment]
thanks.  It does still download, though, correct?  check your downloads folder.  The error is a node redirection error (to save the obj on the server - not implemented yet) that shouldn't be interfering with the local blob download of your obj file.
I'll haven't done anything re A-Frame or Meshmixer.  could you specify your use case?

**Comment by cindyloo** [comment]
remove half-implemented code for now

**Comment by jimbo00000** [comment]
It's likely that A-Frame and Meshmixer don't support the lesser-known "line" elements of the obj file format that vrdoodler uses. They are not meshes per se.

**Comment by armthethinker** [comment]
Thanks for the feedback!
